# Generated by Django 3.2.5 on 2021-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210714_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
