# Generated by Django 3.2.5 on 2021-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_quiz_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('MCQ', 'MCQ')], default='MCQ', max_length=10),
        ),
    ]
